config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/runscan'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def runscan
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<div class="jumbotron" style="background-color: rgba(87, 174, 255, 0.3); padding-bottom: 5px">
  <h1 class="display-6" style="padding-left: 10px">mScan API</h1>
</div>

app/views/home/_vertNav.html.erb
<div style="float:left; width: 23em; margin-right:5em; padding-bottom:5em; padding-left:5px; padding-top:4em; background-color:#cad8ed">
<nav class="nav flex-column">
  <button class="btn btn-lg d-inline-flex align-items-right rounded" data-bs-toggle="collapse" data-bs-target="#start-collapse" aria-expanded="false" id="st">Getting Started</button>

  <div class="collapse show" id="start-collapse">

          <ul class="pb-2 lg">
              <li><%= link_to "RunScan", home_runscan_path %></li>
              <li><a  class="d-inline-flex align-items-right rounded navSubItm">Containers</a></li>
              <li><a  class="d-inline-flex align-items-right rounded navSubItm">Grid</a></li>
          </ul>
          
        </div> 
</nav>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/runscan.html.erb
<div style="padding-top:5em; width: 90em; float:left">
<div class="column">
<h1>RunScan</h1>
<p>Find me in app/views/home/index.html.erb</p>
<p>Find me in app/views/home/index.html.erb</p> <br/>
<br/> <br/>
<p>Find me in app/views/home/index.html.erb</p> <br/> <br/> <br/> <br/><br/><br/><br/><br/> <p>Find me in app/views/home/index.html.erb</p>
</div>
<div class="column">

<div class="tab">
  <button class="tablinks" onclick="openCity(event, 'C#')" id="Cclick">C#</button>
  <button class="tablinks" onclick="openCity(event, 'Javascript')">Javascript</button>
  <button class="tablinks" onclick="openCity(event, 'Java')">Java</button>
</div>

<div id="C#" class="tabcontent">
  <h3>C#</h3>
  <code> <pre>C# example code int x = 5  
  some more 
  int x = 6
  var y = 3</pre></code>
</div>

<div id="Javascript" class="tabcontent">
  <h3>Javascript</h3>
  <code> <pre>Section for code examples, int x = 5 </pre></code>
</div>

<div id="Java" class="tabcontent">
  <h3>Java</h3>
  <code> <pre>Section for code examples, int x = 5 </pre></code>
</div>


</div>

</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>MsisDocs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body>
    
   
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
    
    <%= render 'home/header' %>
    <%= render 'home/vertNav' %>
    <%= yield %>

    

  </body>
  <footer>
  <%= javascript_pack_tag 'navCtrl' %>
  </footer>
</html>


<script> 
    function openCity(evt, cityName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
      tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(cityName).style.display = "block";
    evt.currentTarget.className += " active";
  }
  document.getElementById("Cclick").click();
  </script>